1. Customer Orders Analysis

In [1]:
import numpy as np

orders = [12, 17, 20, 25, 30, 18, 23, 12, 15, 19, 17, 21, 25, 27, 30, 22, 28, 33, 24, 26, 28, 25, 24, 29, 30, 27, 26, 22, 23, 29]

orders_array = np.array(orders)
max_day = np.argmax(orders_array) + 1  # Adding 1 since days start at 1
max_orders = orders_array.max()

print(f"Day {max_day} had the highest number of orders: {max_orders}")

Day 18 had the highest number of orders: 33


2. Sales Data Reshaping

In [2]:
sales = np.array([150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100])
reshaped_sales = sales.reshape(4, 5)
print("Reshaped sales data (4 weeks x 5 days):")
print(reshaped_sales)

Reshaped sales data (4 weeks x 5 days):
[[ 150  200  250  300  350]
 [ 400  450  500  550  600]
 [ 650  700  750  800  850]
 [ 900  950 1000 1050 1100]]


3. Temperature Data Transformation

In [3]:
temperatures = np.random.randint(20, 35, 168)  # 7 days, 24 hours each
daily_temps = temperatures.reshape(7, 24)
print("\nTemperature data by day (7 days x 24 hours):")
print(daily_temps)


Temperature data by day (7 days x 24 hours):
[[33 26 21 33 31 25 23 23 26 30 25 21 23 33 26 28 21 29 33 31 33 26 22 22]
 [22 23 26 28 32 20 27 32 27 34 25 23 29 28 29 27 20 28 30 25 31 30 28 29]
 [24 25 33 25 27 32 34 34 33 34 34 29 20 27 22 24 33 29 27 30 20 28 32 27]
 [22 29 27 27 25 33 25 31 21 30 28 27 31 26 32 21 30 20 21 29 31 33 33 20]
 [21 31 29 29 24 31 29 23 29 25 21 25 27 23 26 33 27 24 27 29 21 31 31 32]
 [27 29 31 33 26 26 25 22 28 28 30 23 32 28 26 21 23 28 23 25 25 25 30 34]
 [24 20 27 34 33 34 33 33 28 32 26 21 30 27 31 30 26 29 28 21 26 32 31 28]]


4. Product Inventory Management

In [4]:
inventory = np.random.randint(1, 100, 24)  # 24 products
new_inventory = inventory.reshape(6, 4)
print("\nResized inventory (6 rows x 4 columns):")
print(new_inventory)


Resized inventory (6 rows x 4 columns):
[[26 31 87 13]
 [37 71 15 52]
 [30  7  3 63]
 [86 30 96 92]
 [39 88 99 33]
 [73 38 89 28]]


5. Marketing Campaign Analysis

In [5]:
responses = np.random.randint(50, 200, (5, 3))  # 5 regions, 3 campaigns each
total_responses = responses.sum()
print(f"\nTotal positive responses across all regions: {total_responses}")


Total positive responses across all regions: 2012


6. Website Traffic Analysis

In [6]:
traffic_data = np.random.randint(100, 500, 168)  # 7 days, 24 hours each
daily_traffic = traffic_data.reshape(7, 24)
print("\nWebsite traffic by day (7 days x 24 hours):")
print(daily_traffic)


Website traffic by day (7 days x 24 hours):
[[125 343 202 333 398 217 350 334 165 329 151 298 159 366 415 482 246 180
  473 319 459 315 459 294]
 [122 245 482 312 358 163 126 414 206 385 241 413 167 442 381 423 136 361
  470 306 377 185 151 432]
 [481 330 199 137 376 114 338 274 292 299 156 391 320 169 413 250 105 313
  173 137 365 223 269 463]
 [339 292 476 115 217 307 394 395 302 419 148 241 179 417 472 413 252 215
  397 415 414 332 241 132]
 [449 225 311 488 353 394 424 406 346 426 467 282 403 458 160 407 489 463
  255 180 498 430 342 283]
 [193 399 399 131 426 296 463 326 456 473 369 420 290 334 395 295 244 374
  159 186 192 328 354 226]
 [189 109 450 197 196 194 458 228 277 160 410 226 367 339 445 434 427 357
  338 453 450 175 399 198]]


7. Financial Data Normalization

In [7]:
stock_prices = np.random.randint(100, 200, 30)  # 30 days
normalized_prices = (stock_prices - stock_prices.min()) / (stock_prices.max() - stock_prices.min())
print("\nNormalized stock prices:")
print(normalized_prices)


Normalized stock prices:
[0.83695652 0.42391304 0.70652174 0.55434783 0.13043478 0.86956522
 0.69565217 0.51086957 0.         0.16304348 0.36956522 0.27173913
 0.43478261 0.52173913 0.02173913 0.02173913 0.69565217 0.
 0.40217391 0.48913043 0.82608696 0.67391304 0.06521739 0.5
 0.47826087 0.23913043 0.91304348 0.81521739 1.         0.72826087]


8. Customer Satisfaction Survey

In [8]:
survey_results = np.random.randint(1, 6, 50)  # 10 products, 5 responses each
product_surveys = survey_results.reshape(10, 5)
print("\nSurvey results by product (10 products x 5 responses):")
print(product_surveys)


Survey results by product (10 products x 5 responses):
[[2 1 1 1 4]
 [3 3 2 4 4]
 [2 5 3 2 5]
 [2 4 3 2 5]
 [1 4 2 5 5]
 [1 5 3 3 2]
 [2 3 3 5 2]
 [1 4 1 4 5]
 [1 5 2 1 3]
 [3 3 3 1 2]]



9. E-commerce Data Analysis

In [9]:
sales_data = np.random.randint(1000, 10000, (3, 5, 12))  # 3 categories, 5 products each, 12 months
category_totals = sales_data.sum(axis=(1, 2))
print("\nTotal sales by product category:")
for i, total in enumerate(category_totals):
    print(f"Category {i+1}: {total}")


Total sales by product category:
Category 1: 341745
Category 2: 338347
Category 3: 294939


10. Climate Data Analysis

In [10]:
climate_data = np.random.randint(-10, 35, (4, 30, 12))  # 4 regions, 30 days, 12 months
region_avg = climate_data.mean(axis=(1, 2))
print("\nAverage temperature by region:")
for i, avg in enumerate(region_avg):
    print(f"Region {i+1}: {avg:.2f}°C")


Average temperature by region:
Region 1: 12.39°C
Region 2: 12.34°C
Region 3: 11.43°C
Region 4: 12.50°C
